### ISSUE TITLE
Removes spaces in calc() functions.

### ISSUE THREAD

**Issue by mbi** [zacharyvoase/cssmin#16]
Spaces are removed from expressions like `width: calc(100% + 1.5rem)`, but the spec states that [plus and minus operators require spaces around them](http://dev.w3.org/csswg/css-values/#calc-syntax).

**Comment by alcedo** [comment]
+1

**Comment by kristianroebuck** [comment]
If you're using cssmin and want to get around this issue without having to switch to another minifier you're able to change your CSS from this:

`width: calc(100% + 2px);`

to this:

`width: calc(100% - -2px);`

Not ideal, but it works.

**Comment by razmig** [comment]
I have created a pull request for this issue, i am not sure if it will break things. I have done some testing and seems to work fine #18

**Comment by emyller** [comment]
So, is this project dead? I guess I will just use @razmig's fork instead.
